name: GHPages

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install doxygen python3-sphinx python3-breathe

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Make directory
      shell: bash
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${GITHUB_WORKSPACE} -DENABLE_DOCS=On

    - name: Build docs
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target adiak_doxygen adiak_sphinx

    - name: Fix permissions
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: chmod -v -R og+rX "docs/sphinx/html/"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{github.workspace}}/build/docs/sphinx/html/

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
