name: GHPages

on:
  push:
    branches: [ "adiak-documentation" ]

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install doxygen sphinx-doc breathe-doc

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Make directory
      shell: bash
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake ${GITHUB_WORKSPACE} -DENABLE_DOCS=On

    - name: Build docs
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target adiak_doxygen adiak_sphinx

    - name: Fix permissions
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: chmod -v -R og+rX "docs/sphinx/html/"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      path: ${{github.workspace}}/build/docs/sphinx/html/
